name = "yonote"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "yonote-db"
database_id = "7c2973fc-39d6-486e-99e1-aef639e7774d"

# 环境变量（开发环境）
[vars]
ENVIRONMENT = "development"

# 静态资源配置
[assets]
directory = "./public"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }
